cd /home/zhuonan/code/MedToken
python train.py \
  --model guidedino \
  --run-model guidino-tn3k \
  --dinov3-backbone facebook/dinov3-vits16-pretrain-lvd1689m \
  --tn3k-root data_source/Thyoid/tn3k \
  --batch-size 4 \
  --max-epochs 400 \
  --num-workers 8 \
  --dataloader-mp-context fork \
  --lr 1e-2 \
  --image-size 512 \
  --seg-preprocess dino_strong \
  --loss guide_dc_bce_hinged \
  --weight-guide 0.1 \
  --weight-hinge-d 0.05 \
  --hinge-d-margin 1.0 \
  --hinge-d-kernel-size 3 \
  --lr-scheduler cosine_restart \
  --tokenbook-dropout 0.8 \
  --tokenbook-sample-rate 0.5 \
  --tokenbook-use-ema \
  --no-train-epoch-eval
