cd /home/zhuonan/code/MedToken
python train.py \
  --model guidennwnet \
  --run-model guidennwnet-synapse-init \
  --synapse-root data_source/synapse \
  --dinov3-backbone facebook/dinov3-vits16-pretrain-lvd1689m \
  --loss guide_dc_ce \
  --image-size 512 \
  --batch-size 4 \
  --max-epochs 2000 \
  --seg-preprocess dino_strong \
  --optimizer sgd \
  --lr 1e-2 \
  --weight-decay 3e-5 \
  --weight-guide 0.1 \
  --tokenbook-sample-rate 1.0 \
  --tokenbook-dropout 0.0 \
  --nnwnet-deep-supervision \
  --num-classes 9 \
  --in-chans 3 \
  --no-train-epoch-eval
