cd /home/zhuonan/code/MedToken
python train.py \
  --model guidedino \
  --run-model guidedino-tn3k-lora \
  --tn3k-root data_source/Thyoid/tn3k \
  --dinov3-backbone facebook/dinov3-vits16-pretrain-lvd1689m \
  --loss guide_dc_bce \
  --image-size 512 \
  --batch-size 4 \
  --max-epochs 400 \
  --seg-preprocess dino_strong \
  --optimizer adamw \
  --lr 1e-4 \
  --lr-lora 5e-4 \
  --lr-head 1e-4 \
  --weight-decay 3e-5 \
  --dice-do-bg \
  --weight-guide 0.1 \
  --tokenbook-sample-rate 1.0 \
  --tokenbook-dropout 0.0 \
  --dinov3-lora-enable \
  --dinov3-lora-r 8 \
  --dinov3-lora-alpha 16 \
  --dinov3-lora-dropout 0.05 \
  --no-train-epoch-eval
